### ISSUE TITLE
Loading indication when submitting public share

### ISSUE THREAD

**Issue by LukasLohoff** [o2r-project/o2r-platform#69]
When uploading large files via public share, it's not possible to see an indication that something is happening/loading. 

I guess a "progress bar" similar to the zip upload won't be possible - there is no way to find out the progress.

What do you think?

**Comment by nuest** [comment]
Afaics the issue is that we must provide the upload status on the server side then. And the upload API would have to return immediately with a response and provide state information of the upload (ideally via a WebSocket). 

The real problem is that on the server side we do not have a progress information at the moment because we're loading via webdav, see https://github.com/o2r-project/o2r-loader/blob/master/lib/steps.js#L43 (note for later: https://www.npmjs.com/package/progress-stream might help).

I really like this feature, I don't think it will have a high priority as of now.

@jansule If this becomes a desired feature from the UI side, please let us know.

**Comment by MarkusKonk** [comment]
Afaik, we had a user story for that issue but assigned a low priority for it, particularly for the first project phase...

**Comment by nuest** [comment]
I would prefer if we do not close issues because of low priority, but we give them low priority.
