### ISSUE TITLE
Highlight required metadata fields

### ISSUE THREAD

**Issue by MarkusKonk** [o2r-project/o2r-platform#84]
Some metadata attributes are required. These should be highlighted in red ín addition to the asterisk.

**Comment by jansule** [comment]
@MarkusKonk Should these attributes be highlighted immediately, or only after a user switched tabs? I would rather avoid highlighting these attributes immediately. Since all attributes in the first tab are required attributes, I can imagine that it might be intimidating to a user facing a formula where everything is red.

**Comment by MarkusKonk** [comment]
I do not mean to highlight it right at the beginning, rather when I come back after I moved to the next page. There should be something like "required field" in red. Otherwise, I search for missing fields.

**Comment by jansule** [comment]
Alright, then I get it right, now. I will take a look at this.
